@extends('layouts.app')
@section('title','Catat Surat Masuk')
@section('content')
<div class="w-full max-w-5xl"><form method="POST" action="{{route('surat-masuk.store')}}" enctype="multipart/form-data" class="bg-white rounded-2xl border border-gray-200 p-6 lg:p-8 space-y-6">@csrf
@if($errors->any())<div class="rounded-xl bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">@foreach($errors->all() as $e)<p>{{$e}}</p>@endforeach</div>@endif
<div><h2 class="font-display text-xl" style="color:var(--navy)">Data Surat Masuk</h2><p class="text-sm mt-1" style="color:var(--ink-muted)">Catat surat yang diterima sekolah dan siapkan untuk disposisi.</p></div>
<div class="grid md:grid-cols-2 gap-5"><div><label class="block text-sm font-medium mb-1.5">Nomor Surat Asal</label><input name="nomor_surat_asal" value="{{old('nomor_surat_asal')}}" class="w-full rounded-xl border border-gray-300 px-3 py-3"></div><div><label class="block text-sm font-medium mb-1.5">Asal Instansi <span class="text-red-500">*</span></label><input name="asal_instansi" value="{{old('asal_instansi')}}" class="w-full rounded-xl border border-gray-300 px-3 py-3" required></div><div><label class="block text-sm font-medium mb-1.5">Kategori <span class="text-red-500">*</span></label><select name="id_kategori" class="w-full rounded-xl border border-gray-300 px-3 py-3" required><option value="">-- Pilih --</option>@foreach($kategoriList as $k)<option value="{{$k->id_kategori}}" {{old('id_kategori')==$k->id_kategori?'selected':''}}>{{$k->nama_kategori}}</option>@endforeach</select></div><div><label class="block text-sm font-medium mb-1.5">Klasifikasi <span class="text-red-500">*</span></label><select name="id_klasifikasi" class="w-full rounded-xl border border-gray-300 px-3 py-3" required>@foreach($klasifikasiList as $k)<option value="{{$k->id_klasifikasi}}" {{old('id_klasifikasi')==$k->id_klasifikasi?'selected':''}}>{{$k->kode_klasifikasi}} - {{$k->nama_klasifikasi}}</option>@endforeach</select></div><div class="md:col-span-2"><label class="block text-sm font-medium mb-1.5">Perihal <span class="text-red-500">*</span></label><input name="perihal" value="{{old('perihal')}}" class="w-full rounded-xl border border-gray-300 px-3 py-3" required></div><div><label class="block text-sm font-medium mb-1.5">Tanggal Surat</label><input type="date" name="tanggal_surat" value="{{old('tanggal_surat')}}" class="w-full rounded-xl border border-gray-300 px-3 py-3"></div><div><label class="block text-sm font-medium mb-1.5">Tanggal Diterima <span class="text-red-500">*</span></label><input type="date" name="tanggal_diterima" value="{{old('tanggal_diterima',now()->format('Y-m-d'))}}" class="w-full rounded-xl border border-gray-300 px-3 py-3" required></div><div><label class="block text-sm font-medium mb-1.5">Sifat Surat</label><select name="sifat_surat" class="w-full rounded-xl border border-gray-300 px-3 py-3">@foreach(['biasa','penting','segera','rahasia'] as $s)<option value="{{$s}}">{{ucfirst($s)}}</option>@endforeach</select></div><div><label class="block text-sm font-medium mb-1.5">Scan Surat</label><input type="file" name="file_scan" accept=".pdf,.jpg,.jpeg,.png" class="w-full rounded-xl border border-gray-300 px-3 py-2.5 text-sm"></div></div>
<div class="flex justify-end gap-3 border-t border-gray-100 pt-5"><a href="{{route('surat-masuk.index')}}" class="px-5 py-2.5 rounded-xl border border-gray-300 text-sm">Batal</a><button class="px-6 py-2.5 rounded-xl text-white text-sm font-medium" style="background:var(--navy)">Simpan Surat Masuk</button></div>
</form></div>
@endsection
