@extends('layouts.app')
@section('title','Surat Masuk')
@section('content')
<div class="w-full">
@if(session('sukses'))<div class="mb-5 rounded-xl bg-green-50 border border-green-200 text-green-700 px-5 py-4 text-sm">{{session('sukses')}}</div>@endif
<div class="flex flex-wrap items-center justify-between gap-4 mb-5"><div><h2 class="font-display text-xl" style="color:var(--navy)">Daftar Surat Masuk</h2><p class="text-sm mt-1" style="color:var(--ink-muted)">Pencatatan surat, disposisi, tindak lanjut, dan arsip.</p></div><a href="{{route('surat-masuk.create')}}" class="px-5 py-2.5 rounded-xl text-white text-sm font-medium" style="background:var(--navy)">+ Catat Surat Masuk</a></div>
<div class="flex flex-wrap gap-2 mb-4">@foreach([''=>'Semua','baru'=>'Baru','didisposisi'=>'Didisposisi','diproses'=>'Diproses','selesai'=>'Selesai','diarsipkan'=>'Diarsipkan'] as $v=>$l)<a href="{{route('surat-masuk.index',$v?['status'=>$v]:[])}}" class="text-xs px-3.5 py-2 rounded-full border {{($filterStatus===$v||(!$filterStatus&&!$v))?'text-white border-transparent':'bg-white border-gray-300'}}" style="{{($filterStatus===$v||(!$filterStatus&&!$v))?'background:var(--navy)':''}}">{{$l}}</a>@endforeach</div>
<div class="bg-white rounded-2xl border border-gray-200 overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50"><tr class="text-left"><th class="px-5 py-4">Agenda</th><th class="px-5 py-4">Asal</th><th class="px-5 py-4">Perihal</th><th class="px-5 py-4">Tanggal</th><th class="px-5 py-4">Status</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($suratMasuk as $s)<tr class="hover:bg-gray-50"><td class="px-5 py-4 font-mono text-xs">{{$s->nomor_surat_masuk}}</td><td class="px-5 py-4">{{$s->asal_instansi}}</td><td class="px-5 py-4"><a href="{{route('surat-masuk.show',$s)}}" class="font-medium hover:underline">{{$s->perihal}}</a></td><td class="px-5 py-4" style="color:var(--ink-muted)">{{$s->tanggal_diterima?->format('d/m/Y')}}</td><td class="px-5 py-4">{{$s->status}}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center" style="color:var(--ink-muted)">Belum ada surat masuk.</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{$suratMasuk->links()}}</div>
</div>
@endsection
