@extends('layouts.app')
@section('title','Detail Surat Masuk')
@section('content')
<div class="w-full space-y-5">
@if(session('sukses'))<div class="rounded-xl bg-green-50 border border-green-200 text-green-700 px-5 py-4 text-sm">{{session('sukses')}}</div>@endif
<div class="bg-white rounded-2xl border border-gray-200 p-6 lg:p-8"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs uppercase tracking-wider" style="color:var(--gold)">Surat Masuk</p><h2 class="font-display text-2xl mt-1" style="color:var(--navy)">{{$suratMasuk->perihal}}</h2><p class="text-sm mt-2" style="color:var(--ink-muted)">Dari {{$suratMasuk->asal_instansi}} · Agenda {{$suratMasuk->nomor_surat_masuk}}</p></div>@php $w=['baru'=>'#C9972F','didisposisi'=>'#16324F','diproses'=>'#16324F','selesai'=>'#2F6B4F','diarsipkan'=>'#767C86']; @endphp<span class="text-xs px-3 py-1.5 rounded-full" style="background:{{$w[$suratMasuk->status]}}22;color:{{$w[$suratMasuk->status]}}">{{ucfirst($suratMasuk->status)}}</span></div><div class="grid md:grid-cols-4 gap-4 mt-6 text-sm"><div><p class="text-xs" style="color:var(--ink-muted)">Nomor Asal</p><p class="mt-1">{{$suratMasuk->nomor_surat_asal??'-'}}</p></div><div><p class="text-xs" style="color:var(--ink-muted)">Tanggal Surat</p><p class="mt-1">{{$suratMasuk->tanggal_surat?->format('d/m/Y')??'-'}}</p></div><div><p class="text-xs" style="color:var(--ink-muted)">Diterima</p><p class="mt-1">{{$suratMasuk->tanggal_diterima?->format('d/m/Y')}}</p></div><div><p class="text-xs" style="color:var(--ink-muted)">Sifat</p><p class="mt-1">{{ucfirst($suratMasuk->sifat_surat)}}</p></div></div>@if($suratMasuk->file_scan_path)<a target="_blank" href="{{asset('storage/'.$suratMasuk->file_scan_path)}}" class="inline-block mt-5 text-sm font-medium" style="color:var(--navy)">Buka scan surat ↗</a>@endif</div>
@if(in_array(auth()->user()->role,['admin_tu','super_admin','kepala_sekolah']))<div class="bg-white rounded-2xl border border-gray-200 p-6"><h3 class="font-display text-lg" style="color:var(--navy)">Buat Disposisi</h3><form method="POST" action="{{route('surat-masuk.disposisi.store',$suratMasuk)}}" class="mt-5 grid md:grid-cols-3 gap-4">@csrf<div><label class="block text-sm font-medium mb-1.5">Tujuan</label><select name="tujuan_tipe" id="tujuan_tipe" onchange="ubahTujuan()" class="w-full rounded-xl border border-gray-300 px-3 py-3"><option value="pegawai">Pegawai</option><option value="unit">Unit Kerja</option></select></div><div><label class="block text-sm font-medium mb-1.5">Penerima</label><select name="tujuan_id" id="tujuan_id" class="w-full rounded-xl border border-gray-300 px-3 py-3">@foreach($pegawaiList as $p)<option data-tipe="pegawai" value="{{$p->id_pegawai}}">{{$p->nama_lengkap}}</option>@endforeach @foreach($unitList as $u)<option data-tipe="unit" value="{{$u->id_unit}}" style="display:none">{{$u->nama_unit}}</option>@endforeach</select></div><div><label class="block text-sm font-medium mb-1.5">Instruksi</label><input name="instruksi" class="w-full rounded-xl border border-gray-300 px-3 py-3" placeholder="Mohon ditindaklanjuti"></div><div class="md:col-span-3"><label class="block text-sm font-medium mb-1.5">Catatan</label><textarea name="catatan" rows="2" class="w-full rounded-xl border border-gray-300 px-3 py-3"></textarea></div><div class="md:col-span-3 flex justify-end"><button class="px-6 py-2.5 rounded-xl text-white text-sm" style="background:var(--navy)">Kirim Disposisi</button></div></form></div>@endif
@if($suratMasuk->disposisi->isNotEmpty())<div><h3 class="font-display text-lg mb-3" style="color:var(--navy)">Riwayat Disposisi</h3><div class="space-y-3">@foreach($suratMasuk->disposisi as $d)<div class="bg-white rounded-2xl border border-gray-200 p-5 flex flex-wrap justify-between gap-3"><div><p class="text-sm font-medium">Ke: {{$d->tujuan_label}}</p><p class="text-xs mt-1" style="color:var(--ink-muted)">Dari {{$d->pemberiDisposisi->nama_lengkap??'-'}} · {{$d->tanggal_disposisi?->diffForHumans()}}</p>@if($d->instruksi)<p class="text-sm mt-2">{{$d->instruksi}}</p>@endif</div><div class="flex items-center gap-3"><span class="text-xs">{{ucfirst($d->status)}}</span>@if($d->status!=='selesai')<form method="POST" action="{{route('disposisi.selesaikan',$d)}}">@csrf<button class="text-xs font-medium" style="color:var(--navy)">Tandai Selesai</button></form>@endif</div></div>@endforeach</div></div>@endif
@if($suratMasuk->status==='selesai' && auth()->user()->role!=='guru')<form method="POST" action="{{route('arsip.surat-masuk',$suratMasuk)}}">@csrf<button class="px-5 py-2.5 rounded-xl text-white text-sm" style="background:var(--navy)">Arsipkan Surat</button></form>@endif
</div>
@push('scripts')<script>function ubahTujuan(){const t=document.getElementById('tujuan_tipe').value;document.querySelectorAll('#tujuan_id option').forEach(o=>o.style.display=o.dataset.tipe===t?'block':'none');const f=document.querySelector('#tujuan_id option[data-tipe="'+t+'"]');if(f)document.getElementById('tujuan_id').value=f.value}ubahTujuan();</script>@endpush
@endsection
